server:
  port: 8080

application:
  server:
    url: http://localhost:8080

docspace:
  server:
    url: http://localhost:8092

spring:
  #  sql:
  #    init:
  #      mode: always
  datasource:
    url: jdbc:mysql://localhost:33060/docspace
    username: keycloak
    password: keycloak
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: none
#    properties:
#      hibernate:
#        generate_statistics: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 3000
          multiplier: 3.0

messaging:
  rabbitmq:
    configuration:
      authorization:
        exchange: authorization.exchange
        queue: authorization.queue
        routing: authorization.routing
        deadExchange: authorization.dead.exchange
        deadQueue: authorization.dead.queue
        deadRouting: authorization.dead.routing
      consent:
        exchange: consent.exchange
        queue: consent.queue
        routing: consent.routing
        deadExchange: consent.dead.exchange
        deadQueue: consent.dead.queue
        deadRouting: consent.dead.routing

logging:
  level:
    root: INFO
    org:
      hibernate:
#        stat: DEBUG
#        SQL: DEBUG
